services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge