services:
  postgres:
    container_name: backend_vlab
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - backend_desafio_vlab:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=postgres
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app

volumes:
  backend_desafio_vlab: